### ISSUE TITLE
Don't let field-level parsing exceptions halt the parser

### ISSUE THREAD

**Issue by hkeeler** [cfpb/hmda-platform#64] opened 2016-02-16 16:14 UTC
As mentioned on https://github.com/cfpb/hmda-platform/pull/63#discussion_r53020374, we need to make sure individual invalid data fields cannot blow up the whole parser.  The exact design of this is TBD.

**Comment by jmarin** [comment] 2016-02-17 16:15
Duplicate of #62

**Closed** 2016-05-26 19:13 UTC
Labels: Parser
