### ISSUE TITLE
Validation (2017): V110 (Parent Mailing Address)

### ISSUE THREAD

**Issue by jmarin** [cfpb/hmda-platform#52] opened 2016-01-28 18:41 UTC
If respondent is a Mortgage Banking Subsidiary (MBS) or a nondepository institution that has an affiliation with a depository institution, then parent name of the MBS or the depository institution that the nondepository institution is affiliated with along with the address, city and zip code must not = blank

**Comment by hkeeler** [comment] 2016-03-08 17:44
Dupe of #105.  Closing.

**Closed by hkeeler** 2016-03-08 17:44 UTC
Labels: Data Validation
