### ISSUE TITLE
Error in 2022 Filing on Dev

### ISSUE THREAD

**Issue by audayshankar** [cfpb/hmda-platform#4280] opened 2021-11-19 15:40 UTC
When uploading a file to 2022 filing in the development environment, the platform does not recognize 2022 as the correct year for Action Taken Date and Application Date and gives a validity edit (v619) 

![image](https://user-images.githubusercontent.com/58990254/142648803-7c3cf518-ee59-4850-89d9-af28bc49d562.png)

![image](https://user-images.githubusercontent.com/58990254/142648700-cc7f7f54-8ba1-435a-9de7-5af44304dcf4.png)

**Comment by audayshankar** [comment] 2021-11-22 22:21
Trying 2022 for Action Taken Date/Application Date for 2022 Q1 filing and it's not working. However, previously using 2021 as the year was working for 2022 filing. that is no longer working either. 

Also, now V602 is incorrectly popping up for 2022-Q1 filing saying that calendar quarter needs to be 4. 

![image](https://user-images.githubusercontent.com/58990254/142943650-b2e08532-b05f-40eb-bb54-722351cfbc5b.png)
@PatrickGoRaft @KennethGudel

**Comment by chynnakeys** [comment] 2022-02-07 17:45
Filer in beta is now having this same issue. I can confirm that filing a 2022 file in annual with 2022 dates is triggering V619-2 

![image](https://user-images.githubusercontent.com/41752348/152843077-56ca8344-d41d-4759-b449-07ed0fce9a29.png)

**Comment by chynnakeys** [comment] 2022-02-23 19:51
Cannot replicate & the issue seems to be solved - closing ticket

**Closed by chynnakeys** 2022-02-23 19:51 UTC
Labels: bug
