### ISSUE TITLE
IRS returns incorrect values in smoke tests

### ISSUE THREAD

**Issue by schbetsy** [cfpb/hmda-platform#979] opened 2017-05-21 15:04 UTC
In this screenshot, the IRS shows 92 total LARs for this submission, but the actual submission only has 10 LARs. I've seen this frequently when uploading multiple files for an institution.

<img width="648" alt="screen shot 2017-05-21 at 11 00 05 am" src="https://cloud.githubusercontent.com/assets/4295388/26284999/b4156072-3e14-11e7-9872-474ca3a8da21.png">

**Comment by schbetsy** [comment] 2017-05-23 14:41
Here's the steps for one way I have generated this bug. Notes: I was using institution `6999998` for all submissions. `HMDA_IS_DEMO` was set to `true`.

1. Clean slate in Postgres: in `psql hmda`, `drop table lars cascade;`, `\q`
1. Start the API in the usual way: In sbt, `clean`, `compile`, `project api`, `reStart` (repeat `reStop`-`reStart` cycle as necessary until the demo data gets populated 😞 )
2. Create submission. upload 90-line file. check irs... total lars = 90. ✅ 
3. Create another submission. upload 400-line file. check irs... total lars = 490. ❌ 
4. Just for fun, do it again: upload 10-line file. irs says total lines = 500. ❌ 

I've also seen it when running the whole docker setup.

**Comment by nickgrippin** [comment] 2017-05-23 16:01
Confirmed, the issue seems to be an intermittent failure to delete the previous LAR submissions from the repository, affecting the IRS report and modified LAR endpoint.

**Comment by nickgrippin** [comment] 2017-05-23 16:30
IRS reporting incorrect values will be addressed in #984

This ticket will stay open in order to address the bug with the modified LAR endpoint.

**Comment by schbetsy** [comment] 2017-06-09 16:23
This seems to be resolved by #1000.

**Comment by nickgrippin** [comment] 2017-06-09 17:10
I agree, that's what I'm seeing as well.  Closing this ticket.

**Closed by nickgrippin** 2017-06-09 17:10 UTC
Labels: bug
