### ISSUE TITLE
Validation (2017): V155 (Respondent E-Mail Address)

### ISSUE THREAD

**Issue by jmarin** [cfpb/hmda-platform#50] opened 2016-01-28 18:20 UTC
A valid e-mail address for the institution must be provided and must be in the format of username@exampledomain.topleveldomain. The e-mail address shall not contain any spaces and must contain only one @ symbol. The e-mail address shall not contain "@.", ".@" and ".." character strings

**Comment by hkeeler** [comment] 2016-03-08 17:41
Dupe of #103.  Closing.

**Comment by hkeeler** [comment] 2016-03-08 17:42
Dupe of #103.  Closing.

**Closed** 2016-03-08 17:42 UTC
Labels: Data Validation
