### ISSUE TITLE
Validation (2017): V145 (Respondent Zip Code)

### ISSUE THREAD

**Issue by jmarin** [cfpb/hmda-platform#49] opened 2016-01-28 18:16 UTC
Respondent zip code format must be NNNNN or NNNNN-NNNN and left justified (*)

(*) copied verbatim, left justification will most likely not be needed

**Comment by hkeeler** [comment] 2016-03-08 17:39
Dupe of #102.  Closing.

**Closed by hkeeler** 2016-03-08 17:39 UTC
Labels: Data Validation
