### ISSUE TITLE
Validation (2017): V112 (Parent Zip Code)

### ISSUE THREAD

**Issue by jmarin** [cfpb/hmda-platform#54] opened 2016-01-28 18:43 UTC
If parent zip code is reported, then the format must be NNNNN or NNNNN-NNNN and left justified (*)

(*) Left justified will not be needed

**Comment by hkeeler** [comment] 2016-03-08 17:46
Dupe of #107.  Closing.

**Closed by hkeeler** 2016-03-08 17:46 UTC
Labels: Data Validation
