### ISSUE TITLE
Validation (2017): V325 (Co-Applicant Sex)

### ISSUE THREAD

**Issue by hkeeler** [cfpb/hmda-platform#153] opened 2016-03-08 17:12 UTC
**Edit #:** V325
**Type:** Validity
**Category:** Loan/Application Register (only)
**Column:** Co-Applicant Sex

~~Applicant sex must = 1, 2, 3, or 4.~~
Co-Applicant sex must = 1,2,3,4, or 5.

Additional resources:
* [FFIEC's 2016 HMDA File Spec](https://www.ffiec.gov/hmda/pdf/spec2016.pdf)
* [FFIEC's 2016 HMDA Edits](https://www.ffiec.gov/hmda/pdf/edit2016.pdf)
* [CFPB's 2017 HMDA File Spec](http://www.consumerfinance.gov/hmda/static/for-filers/2017/2017-HMDA-File-Specifications.pdf)

**Comment by schbetsy** [comment] 2016-05-03 20:52
I think this edit check is mis-copied. The text is currently a duplicate of #152 (V320). I believe it should say "Co-Applicant sex must = 1,2,3,4, or 5". 

This is corroborated by  the [file spec](http://www.consumerfinance.gov/data-research/hmda/static/for-filers/2017/2017-HMDA-File-Specifications.pdf) and the "CFPB Translation of Edit for Programming" in the edit requirements spreadsheet.

**Comment by lesgou** [comment] 2016-05-03 21:27
Thanks for pointing this out. I have updated the appropriate columns in the edit requirements spreadsheet and reposted.

**Comment by schbetsy** [comment] 2016-05-03 21:38
Thank you @lesgou !

I've now updated the text of this issue to reflect what's in the edit requirements spreadsheet.

**Closed** 2016-05-03 23:21 UTC
Labels: Data Validation, Validity Edit
